/**
 * The route manifest. INTEGRATOR-OWNED (ADR-0018).
 *
 * Feature teams do not edit this file — four teams adding routes to one array
 * is the collision the ownership model exists to prevent. Each team builds its
 * screens behind the entry point already listed here and reports if it needs a
 * new top-level route.
 */
export const ROUTES = {
  today: '/',
  workout: '/workout',
  nutrition: '/nutrition',
  insights: '/insights',
  settings: '/settings',
} as const;

export type RouteKey = keyof typeof ROUTES;
